# .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.
# | .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |
# | |   ______     | || |   _____      | || |      __      | || |  ____  ____  | || |   ______     | || |     ____     | || |  ____  ____  | |
# | |  |_   __ \   | || |  |_   _|     | || |     /  \     | || | |_  _||_  _| | || |  |_   _ \    | || |   .'    `.   | || | |_  _||_  _| | |
# | |    | |__) |  | || |    | |       | || |    / /\ \    | || |   \ \  / /   | || |    | |_) |   | || |  /  .--.  \  | || |   \ \  / /   | |
# | |    |  ___/   | || |    | |   _   | || |   / ____ \   | || |    \ \/ /    | || |    |  __'.   | || |  | |    | |  | || |    > `' <    | |
# | |   _| |_      | || |   _| |__/ |  | || | _/ /    \ \_ | || |    _|  |_    | || |   _| |__) |  | || |  \  `--'  /  | || |  _/ /'`\ \_  | |
# | |  |_____|     | || |  |________|  | || ||____|  |____|| || |   |______|   | || |  |_______/   | || |   `.____.'   | || | |____||____| | |
# | |              | || |              | || |              | || |              | || |              | || |              | || |              | |
# | '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |
# '----------------'  '----------------'  '------MADE------'  '--------BY------'  '-----ZUVENO-----'  '----------------'  '----------------'

#Enable it if you need to know about new versions.
update-check: true
